import {
  Student,
  Course,
  StudentCourseGrade,
  Assignment,
  StudentAssignmentRecord,
  WorkflowRule,
  ReminderLog,
  LMSIntegrationConfig,
} from '../src/types.js';

export const initialStudents: Student[] = [
  {
    id: 'stu_1',
    name: 'Alex Rivera',
    email: 'alex.rivera@university.edu',
    phone: '+1 (555) 234-8901',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    major: 'Computer Science',
    year: 'Junior',
    gpa: 2.84,
    riskLevel: 'AT_RISK',
    advisorName: 'Dr. Evelyn Vance',
    advisorEmail: 'e.vance@university.edu',
    notificationPreferences: {
      email: true,
      sms: true,
      push: true,
      webhookUrl: 'https://discord.com/api/webhooks/demo/alex-rivera',
    },
    stats: {
      completedTasks: 14,
      pendingTasks: 4,
      missingTasks: 2,
      resolvedReminders: 8,
    },
  },
  {
    id: 'stu_2',
    name: 'Jordan Lee',
    email: 'jordan.lee@university.edu',
    phone: '+1 (555) 876-4321',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    major: 'Data Science & Applied Math',
    year: 'Sophomore',
    gpa: 2.31,
    riskLevel: 'CRITICAL',
    advisorName: 'Prof. Marcus Brody',
    advisorEmail: 'm.brody@university.edu',
    notificationPreferences: {
      email: true,
      sms: true,
      push: false,
    },
    stats: {
      completedTasks: 9,
      pendingTasks: 5,
      missingTasks: 4,
      resolvedReminders: 3,
    },
  },
  {
    id: 'stu_3',
    name: 'Maya Chen',
    email: 'maya.chen@university.edu',
    phone: '+1 (555) 456-7890',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    major: 'Biomedical Engineering',
    year: 'Senior',
    gpa: 3.92,
    riskLevel: 'ON_TRACK',
    advisorName: 'Dr. Evelyn Vance',
    advisorEmail: 'e.vance@university.edu',
    notificationPreferences: {
      email: true,
      sms: false,
      push: true,
    },
    stats: {
      completedTasks: 22,
      pendingTasks: 3,
      missingTasks: 0,
      resolvedReminders: 12,
    },
  },
  {
    id: 'stu_4',
    name: 'Samantha Wu',
    email: 'samantha.wu@university.edu',
    phone: '+1 (555) 345-6712',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    major: 'Neuroscience & Biology',
    year: 'Junior',
    gpa: 3.45,
    riskLevel: 'ON_TRACK',
    advisorName: 'Dr. Evelyn Vance',
    advisorEmail: 'e.vance@university.edu',
    notificationPreferences: {
      email: true,
      sms: true,
      push: true,
    },
    stats: {
      completedTasks: 18,
      pendingTasks: 3,
      missingTasks: 1,
      resolvedReminders: 9,
    },
  },
  {
    id: 'stu_5',
    name: 'Marcus Johnson',
    email: 'marcus.j@university.edu',
    phone: '+1 (555) 987-1234',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    major: 'Software Engineering',
    year: 'Sophomore',
    gpa: 3.12,
    riskLevel: 'AT_RISK',
    advisorName: 'Prof. Marcus Brody',
    advisorEmail: 'm.brody@university.edu',
    notificationPreferences: {
      email: true,
      sms: true,
      push: true,
    },
    stats: {
      completedTasks: 15,
      pendingTasks: 4,
      missingTasks: 2,
      resolvedReminders: 7,
    },
  },
];

export const initialCourses: Course[] = [
  {
    id: 'crs_1',
    code: 'CS 301',
    title: 'Algorithms & Complexity',
    term: 'Fall 2026',
    instructor: 'Prof. Sarah Jenkins',
    instructorEmail: 's.jenkins@university.edu',
    credits: 4,
    color: '#6366f1', // Indigo
    schedule: 'Mon/Wed 10:00 - 11:50 AM',
    lmsSource: 'CANVAS',
    weights: {
      homework: 25,
      quizzes: 15,
      exams: 35,
      projects: 20,
      participation: 5,
    },
  },
  {
    id: 'crs_2',
    code: 'MATH 240',
    title: 'Linear Algebra & Matrix Theory',
    term: 'Fall 2026',
    instructor: 'Dr. Michael Chang',
    instructorEmail: 'm.chang@university.edu',
    credits: 4,
    color: '#06b6d4', // Cyan
    schedule: 'Tue/Thu 1:30 - 3:20 PM',
    lmsSource: 'CANVAS',
    weights: {
      homework: 20,
      quizzes: 20,
      exams: 40,
      projects: 15,
      participation: 5,
    },
  },
  {
    id: 'crs_3',
    code: 'BIO 110',
    title: 'Cellular & Molecular Biology',
    term: 'Fall 2026',
    instructor: 'Dr. Aris Thorne',
    instructorEmail: 'a.thorne@university.edu',
    credits: 4,
    color: '#10b981', // Emerald
    schedule: 'Mon/Wed/Fri 9:00 - 9:50 AM',
    lmsSource: 'BLACKBOARD',
    weights: {
      homework: 15,
      quizzes: 15,
      exams: 40,
      projects: 25,
      participation: 5,
    },
  },
  {
    id: 'crs_4',
    code: 'ENG 102',
    title: 'Academic Writing & Tech Rhetoric',
    term: 'Fall 2026',
    instructor: 'Prof. Clara Oswald',
    instructorEmail: 'c.oswald@university.edu',
    credits: 3,
    color: '#f59e0b', // Amber
    schedule: 'Tue/Thu 11:00 - 12:15 PM',
    lmsSource: 'GOOGLE_CLASSROOM',
    weights: {
      homework: 20,
      quizzes: 10,
      exams: 20,
      projects: 40,
      participation: 10,
    },
  },
];

export const initialStudentGrades: StudentCourseGrade[] = [
  // Alex Rivera (stu_1)
  {
    studentId: 'stu_1',
    courseId: 'crs_1',
    currentPercentage: 68.5,
    letterGrade: 'D+',
    previousPercentage: 74.0,
    trend: 'DOWN',
    lastGradedAt: '2026-08-27T14:30:00Z',
  },
  {
    studentId: 'stu_1',
    courseId: 'crs_2',
    currentPercentage: 78.2,
    letterGrade: 'C+',
    previousPercentage: 76.5,
    trend: 'UP',
    lastGradedAt: '2026-08-26T18:00:00Z',
  },
  {
    studentId: 'stu_1',
    courseId: 'crs_3',
    currentPercentage: 86.4,
    letterGrade: 'B',
    previousPercentage: 85.0,
    trend: 'STABLE',
    lastGradedAt: '2026-08-25T11:20:00Z',
  },
  {
    studentId: 'stu_1',
    courseId: 'crs_4',
    currentPercentage: 91.0,
    letterGrade: 'A-',
    previousPercentage: 91.0,
    trend: 'STABLE',
    lastGradedAt: '2026-08-24T16:45:00Z',
  },

  // Jordan Lee (stu_2)
  {
    studentId: 'stu_2',
    courseId: 'crs_1',
    currentPercentage: 62.0,
    letterGrade: 'D',
    previousPercentage: 69.5,
    trend: 'DOWN',
    lastGradedAt: '2026-08-27T14:30:00Z',
  },
  {
    studentId: 'stu_2',
    courseId: 'crs_2',
    currentPercentage: 58.4,
    letterGrade: 'F',
    previousPercentage: 64.0,
    trend: 'DOWN',
    lastGradedAt: '2026-08-26T18:00:00Z',
  },
  {
    studentId: 'stu_2',
    courseId: 'crs_4',
    currentPercentage: 75.0,
    letterGrade: 'C',
    previousPercentage: 73.0,
    trend: 'UP',
    lastGradedAt: '2026-08-24T16:45:00Z',
  },

  // Maya Chen (stu_3)
  {
    studentId: 'stu_3',
    courseId: 'crs_1',
    currentPercentage: 96.8,
    letterGrade: 'A',
    previousPercentage: 95.5,
    trend: 'UP',
    lastGradedAt: '2026-08-27T14:30:00Z',
  },
  {
    studentId: 'stu_3',
    courseId: 'crs_2',
    currentPercentage: 94.2,
    letterGrade: 'A',
    previousPercentage: 94.0,
    trend: 'STABLE',
    lastGradedAt: '2026-08-26T18:00:00Z',
  },
  {
    studentId: 'stu_3',
    courseId: 'crs_3',
    currentPercentage: 98.0,
    letterGrade: 'A+',
    previousPercentage: 97.2,
    trend: 'UP',
    lastGradedAt: '2026-08-25T11:20:00Z',
  },
  {
    studentId: 'stu_3',
    courseId: 'crs_4',
    currentPercentage: 92.5,
    letterGrade: 'A-',
    previousPercentage: 92.0,
    trend: 'STABLE',
    lastGradedAt: '2026-08-24T16:45:00Z',
  },
];

export const initialAssignments: Assignment[] = [
  // CS 301
  {
    id: 'asg_101',
    courseId: 'crs_1',
    title: 'Problem Set 4: Dynamic Programming & Memoization',
    description: 'Implement bottom-up DP algorithms for Knapsack and Matrix Chain Multiplication in Python.',
    type: 'ASSIGNMENT',
    dueDate: '2026-08-27T23:59:00Z', // Yesterday (Overdue/Missing for some)
    pointsPossible: 100,
    weightPercentage: 10,
    estimatedMinutes: 180,
    submissionLink: 'https://canvas.university.edu/courses/301/assignments/101',
  },
  {
    id: 'asg_102',
    courseId: 'crs_1',
    title: 'Midterm Exam: Graph Theory & Shortest Paths',
    description: 'Comprehensive 90-minute proctored exam covering BFS, DFS, Dijkstra, Bellman-Ford, and A*.',
    type: 'MIDTERM',
    dueDate: '2026-08-30T10:00:00Z', // In 2 days! High weight
    pointsPossible: 150,
    weightPercentage: 25,
    estimatedMinutes: 90,
    submissionLink: 'https://canvas.university.edu/courses/301/quizzes/102',
  },
  {
    id: 'asg_103',
    courseId: 'crs_1',
    title: 'Lab 5: Minimum Spanning Trees Benchmark',
    description: 'Benchmarking Kruskal vs Prim on sparse vs dense graphs with visualization.',
    type: 'LAB',
    dueDate: '2026-09-03T23:59:00Z',
    pointsPossible: 50,
    weightPercentage: 5,
    prerequisiteId: 'asg_101',
    estimatedMinutes: 120,
    submissionLink: 'https://canvas.university.edu/courses/301/assignments/103',
  },

  // MATH 240
  {
    id: 'asg_201',
    courseId: 'crs_2',
    title: 'Homework 6: Eigenvalues & Diagonalization',
    description: 'Compute characteristic polynomials, eigenspaces, and verify diagonalization theorems.',
    type: 'ASSIGNMENT',
    dueDate: '2026-08-28T23:59:00Z', // Tonight! (Due in ~14h)
    pointsPossible: 80,
    weightPercentage: 8,
    estimatedMinutes: 150,
    submissionLink: 'https://canvas.university.edu/courses/240/assignments/201',
  },
  {
    id: 'asg_202',
    courseId: 'crs_2',
    title: 'Quiz 3: Orthogonality & Gram-Schmidt',
    description: 'Timed 30-minute online quiz on inner product spaces and projection matrices.',
    type: 'QUIZ',
    dueDate: '2026-08-29T18:00:00Z', // Tomorrow
    pointsPossible: 40,
    weightPercentage: 6,
    prerequisiteId: 'asg_201',
    estimatedMinutes: 45,
    submissionLink: 'https://canvas.university.edu/courses/240/quizzes/202',
  },
  {
    id: 'asg_203',
    courseId: 'crs_2',
    title: 'Capstone Term Project: SVD Image Compression',
    description: 'Use Singular Value Decomposition to compress high-res image datasets and analyze rank approximation.',
    type: 'PROJECT',
    dueDate: '2026-09-10T23:59:00Z',
    pointsPossible: 200,
    weightPercentage: 20,
    estimatedMinutes: 360,
    submissionLink: 'https://canvas.university.edu/courses/240/assignments/203',
  },

  // BIO 110
  {
    id: 'asg_301',
    courseId: 'crs_3',
    title: 'Lab Report 3: CRISPR/Cas9 Gene Splicing Simulation',
    description: 'Analyze gel electrophoresis outputs and submit full scientific report with error bounds.',
    type: 'LAB',
    dueDate: '2026-08-29T12:00:00Z', // Tomorrow noon
    pointsPossible: 100,
    weightPercentage: 12,
    estimatedMinutes: 180,
    submissionLink: 'https://blackboard.university.edu/webapps/bio110/lab3',
  },
  {
    id: 'asg_302',
    courseId: 'crs_3',
    title: 'Discussion Post: Bioethics in Genetic Engineering',
    description: 'Post 400-word response to case study #4 and reply to two peer submissions.',
    type: 'DISCUSSION',
    dueDate: '2026-08-31T23:59:00Z',
    pointsPossible: 30,
    weightPercentage: 3,
    estimatedMinutes: 45,
    submissionLink: 'https://blackboard.university.edu/webapps/bio110/disc4',
  },

  // ENG 102
  {
    id: 'asg_401',
    courseId: 'crs_4',
    title: 'Draft 2: Peer Review of Annotated Bibliography',
    description: 'Review 3 peers research papers on AI in Higher Education with rubric feedback.',
    type: 'ASSIGNMENT',
    dueDate: '2026-08-26T23:59:00Z', // Overdue
    pointsPossible: 50,
    weightPercentage: 10,
    estimatedMinutes: 90,
    submissionLink: 'https://classroom.google.com/c/eng102/a/401',
  },
  {
    id: 'asg_402',
    courseId: 'crs_4',
    title: 'Final Research Proposal: Technology & Ethics',
    description: 'Submit 8-10 page formal research thesis proposal with 15+ peer-reviewed citations.',
    type: 'PROJECT',
    dueDate: '2026-09-08T23:59:00Z',
    pointsPossible: 150,
    weightPercentage: 25,
    estimatedMinutes: 300,
    submissionLink: 'https://classroom.google.com/c/eng102/a/402',
  },
];

export const initialStudentAssignments: StudentAssignmentRecord[] = [
  // Alex Rivera (stu_1)
  {
    id: 'sar_101_1',
    studentId: 'stu_1',
    assignmentId: 'asg_101',
    courseId: 'crs_1',
    status: 'MISSING',
    reminderSentCount: 2,
    lastReminderSentAt: '2026-08-28T08:00:00Z',
  },
  {
    id: 'sar_102_1',
    studentId: 'stu_1',
    assignmentId: 'asg_102',
    courseId: 'crs_1',
    status: 'PENDING',
    reminderSentCount: 1,
    lastReminderSentAt: '2026-08-28T09:00:00Z',
  },
  {
    id: 'sar_201_1',
    studentId: 'stu_1',
    assignmentId: 'asg_201',
    courseId: 'crs_2',
    status: 'PENDING',
    reminderSentCount: 1,
    lastReminderSentAt: '2026-08-27T16:00:00Z',
  },
  {
    id: 'sar_202_1',
    studentId: 'stu_1',
    assignmentId: 'asg_202',
    courseId: 'crs_2',
    status: 'PENDING',
    reminderSentCount: 0,
  },
  {
    id: 'sar_301_1',
    studentId: 'stu_1',
    assignmentId: 'asg_301',
    courseId: 'crs_3',
    status: 'PENDING',
    reminderSentCount: 1,
    lastReminderSentAt: '2026-08-28T07:30:00Z',
  },
  {
    id: 'sar_401_1',
    studentId: 'stu_1',
    assignmentId: 'asg_401',
    courseId: 'crs_4',
    status: 'COMPLETED',
    pointsEarned: 48,
    submittedAt: '2026-08-26T21:15:00Z',
    gradedAt: '2026-08-27T10:00:00Z',
    feedback: 'Excellent critical feedback on peer methodology.',
    reminderSentCount: 1,
  },

  // Jordan Lee (stu_2)
  {
    id: 'sar_101_2',
    studentId: 'stu_2',
    assignmentId: 'asg_101',
    courseId: 'crs_1',
    status: 'MISSING',
    reminderSentCount: 3,
    lastReminderSentAt: '2026-08-28T08:30:00Z',
  },
  {
    id: 'sar_102_2',
    studentId: 'stu_2',
    assignmentId: 'asg_102',
    courseId: 'crs_1',
    status: 'PENDING',
    reminderSentCount: 2,
    lastReminderSentAt: '2026-08-28T09:00:00Z',
  },
  {
    id: 'sar_201_2',
    studentId: 'stu_2',
    assignmentId: 'asg_201',
    courseId: 'crs_2',
    status: 'MISSING',
    reminderSentCount: 2,
    lastReminderSentAt: '2026-08-28T06:00:00Z',
  },
  {
    id: 'sar_202_2',
    studentId: 'stu_2',
    assignmentId: 'asg_202',
    courseId: 'crs_2',
    status: 'PENDING',
    reminderSentCount: 1,
    lastReminderSentAt: '2026-08-27T12:00:00Z',
  },
  {
    id: 'sar_401_2',
    studentId: 'stu_2',
    assignmentId: 'asg_401',
    courseId: 'crs_4',
    status: 'MISSING',
    reminderSentCount: 2,
    lastReminderSentAt: '2026-08-27T18:00:00Z',
  },

  // Maya Chen (stu_3)
  {
    id: 'sar_101_3',
    studentId: 'stu_3',
    assignmentId: 'asg_101',
    courseId: 'crs_1',
    status: 'COMPLETED',
    pointsEarned: 98,
    submittedAt: '2026-08-27T15:00:00Z',
    gradedAt: '2026-08-27T18:00:00Z',
    feedback: 'Flawless dynamic programming runtime complexity proofs.',
    reminderSentCount: 0,
  },
  {
    id: 'sar_102_3',
    studentId: 'stu_3',
    assignmentId: 'asg_102',
    courseId: 'crs_1',
    status: 'PENDING',
    reminderSentCount: 1,
    lastReminderSentAt: '2026-08-28T09:00:00Z',
  },
  {
    id: 'sar_201_3',
    studentId: 'stu_3',
    assignmentId: 'asg_201',
    courseId: 'crs_2',
    status: 'COMPLETED',
    pointsEarned: 80,
    submittedAt: '2026-08-28T08:15:00Z',
    gradedAt: '2026-08-28T09:00:00Z',
    reminderSentCount: 0,
  },
  {
    id: 'sar_301_3',
    studentId: 'stu_3',
    assignmentId: 'asg_301',
    courseId: 'crs_3',
    status: 'PENDING',
    reminderSentCount: 0,
  },
];

export const initialWorkflowRules: WorkflowRule[] = [
  {
    id: 'rule_1',
    name: 'Overdue Assignment Nudge & Action Link',
    description: 'Triggers when an assignment past due date is marked MISSING in the university gradebook.',
    enabled: true,
    triggerType: 'MISSING_ASSIGNMENT',
    conditions: {},
    actions: {
      channels: ['EMAIL', 'IN_APP', 'PUSH'],
      urgencyLevel: 'HIGH',
      templateSubject: '⚠️ Action Required: Missing Assignment in {{courseCode}}',
      templateBody: 'Hi {{studentName}}, our automated system noticed "{{assignmentTitle}}" for {{courseCode}} is overdue. Late submissions still receive up to 80% credit. Click below to review submission instructions or contact {{instructorName}}.',
      useAIPersonalization: true,
      alertAdvisor: false,
      suggestStudyPlan: true,
    },
    cooldownHours: 24,
    timesTriggered: 34,
    resolvedActionsCount: 26,
    lastTriggeredAt: '2026-08-28T08:30:00Z',
  },
  {
    id: 'rule_2',
    name: 'Major Assessment 48-Hour Study Countdown',
    description: 'Sends study reminders for exams and capstone projects carrying >= 20% course weight within 48 hours.',
    enabled: true,
    triggerType: 'HIGH_WEIGHT_ASSESSMENT',
    conditions: {
      deadlineHoursBefore: 48,
      minWeightPercentage: 20,
    },
    actions: {
      channels: ['EMAIL', 'SMS', 'IN_APP'],
      urgencyLevel: 'URGENT',
      templateSubject: '🎯 48h Countdown: {{assignmentTitle}} ({{weightPercentage}}% of Grade)',
      templateBody: 'Hello {{studentName}}, your upcoming {{assignmentType}} for {{courseCode}} is in 48 hours. It carries {{weightPercentage}}% of your final grade. Access the recommended AI study sprint breakdown now.',
      useAIPersonalization: true,
      alertAdvisor: false,
      suggestStudyPlan: true,
    },
    cooldownHours: 24,
    timesTriggered: 18,
    resolvedActionsCount: 15,
    lastTriggeredAt: '2026-08-28T09:00:00Z',
  },
  {
    id: 'rule_3',
    name: 'Academic Safety Net (Grade < 70% Drop Alert)',
    description: 'Detects when a student grade falls below 70% in any course, dispatching student recovery steps and alerting advisor.',
    enabled: true,
    triggerType: 'GRADE_BELOW_THRESHOLD',
    conditions: {
      gradeThresholdPercentage: 70,
    },
    actions: {
      channels: ['EMAIL', 'SMS', 'IN_APP'],
      urgencyLevel: 'URGENT',
      templateSubject: '🚨 Academic Advisory Notice: Grade Alert for {{courseCode}} ({{currentGrade}}%)',
      templateBody: 'Dear {{studentName}}, your current grade in {{courseTitle}} has dipped to {{currentGrade}}%. Your advisor {{advisorName}} has been notified to schedule a 1-on-1 support check-in. Tutoring and office hours are available this week.',
      useAIPersonalization: true,
      alertAdvisor: true,
      suggestStudyPlan: true,
    },
    cooldownHours: 72,
    timesTriggered: 12,
    resolvedActionsCount: 8,
    lastTriggeredAt: '2026-08-27T14:30:00Z',
  },
  {
    id: 'rule_4',
    name: 'Prerequisite Blocker Notification',
    description: 'Warns students if an upcoming lab or quiz relies on an unsubmitted prerequisite homework.',
    enabled: true,
    triggerType: 'PREREQUISITE_INCOMPLETE',
    conditions: {
      requirePrerequisite: true,
    },
    actions: {
      channels: ['IN_APP', 'EMAIL'],
      urgencyLevel: 'MEDIUM',
      templateSubject: '🔗 Prerequisite Task Required for {{assignmentTitle}}',
      templateBody: 'Hi {{studentName}}, before you can begin {{assignmentTitle}} in {{courseCode}}, please ensure prerequisite {{prerequisiteTitle}} is completed.',
      useAIPersonalization: false,
      alertAdvisor: false,
      suggestStudyPlan: false,
    },
    cooldownHours: 24,
    timesTriggered: 7,
    resolvedActionsCount: 6,
    lastTriggeredAt: '2026-08-27T12:00:00Z',
  },
  {
    id: 'rule_5',
    name: '24-Hour Urgent Deadline Nudge',
    description: 'Quick mobile SMS/Push nudge for any pending assignment due within 24 hours.',
    enabled: true,
    triggerType: 'UPCOMING_DEADLINE',
    conditions: {
      deadlineHoursBefore: 24,
    },
    actions: {
      channels: ['SMS', 'PUSH', 'IN_APP'],
      urgencyLevel: 'HIGH',
      templateSubject: '⏰ Due in 24 Hours: {{assignmentTitle}}',
      templateBody: 'Reminder: {{assignmentTitle}} for {{courseCode}} is due tomorrow at {{dueTime}}. Est. completion time: {{estimatedMinutes}} mins.',
      useAIPersonalization: false,
      alertAdvisor: false,
      suggestStudyPlan: false,
    },
    cooldownHours: 12,
    timesTriggered: 45,
    resolvedActionsCount: 41,
    lastTriggeredAt: '2026-08-28T07:30:00Z',
  },
  {
    id: 'rule_6',
    name: 'Excellence & Momentum Commendation',
    description: 'Sends encouraging acknowledgment when student scores >= 90% or improves grade by >5%.',
    enabled: true,
    triggerType: 'GRADE_IMPROVEMENT',
    conditions: {
      gradeThresholdPercentage: 90,
    },
    actions: {
      channels: ['EMAIL', 'IN_APP'],
      urgencyLevel: 'LOW',
      templateSubject: '🎉 Outstanding Work in {{courseCode}} ({{currentGrade}}%)!',
      templateBody: 'Great job {{studentName}}! Your hard work in {{courseTitle}} has raised your grade to an impressive {{currentGrade}}% ({{letterGrade}}). Keep up the great momentum!',
      useAIPersonalization: true,
      alertAdvisor: false,
      suggestStudyPlan: false,
    },
    cooldownHours: 168,
    timesTriggered: 19,
    resolvedActionsCount: 19,
    lastTriggeredAt: '2026-08-26T18:00:00Z',
  },
];

export const initialReminderLogs: ReminderLog[] = [
  {
    id: 'rem_1',
    ruleId: 'rule_1',
    ruleName: 'Overdue Assignment Nudge & Action Link',
    studentId: 'stu_1',
    studentName: 'Alex Rivera',
    studentEmail: 'alex.rivera@university.edu',
    studentPhone: '+1 (555) 234-8901',
    courseId: 'crs_1',
    courseCode: 'CS 301',
    assignmentId: 'asg_101',
    assignmentTitle: 'Problem Set 4: Dynamic Programming & Memoization',
    triggerType: 'MISSING_ASSIGNMENT',
    channel: 'EMAIL',
    urgencyLevel: 'HIGH',
    subject: '⚠️ Action Required: Missing Assignment in CS 301',
    body: 'Hi Alex, our automated workflow detected that Problem Set 4 for CS 301 was not submitted by yesterday\'s midnight deadline. Submitting within 48 hours allows for 80% late credit. Please check the solution outline or reach out to Prof. Sarah Jenkins.',
    aiInsights: 'Student has a 68.5% overall grade in CS 301. Completing this assignment at 80% credit will lift grade by +4.8% to 73.3% (C).',
    createdAt: '2026-08-28T08:00:00Z',
    status: 'DELIVERED',
    openedAt: '2026-08-28T08:14:00Z',
  },
  {
    id: 'rem_2',
    ruleId: 'rule_2',
    ruleName: 'Major Assessment 48-Hour Study Countdown',
    studentId: 'stu_1',
    studentName: 'Alex Rivera',
    studentEmail: 'alex.rivera@university.edu',
    studentPhone: '+1 (555) 234-8901',
    courseId: 'crs_1',
    courseCode: 'CS 301',
    assignmentId: 'asg_102',
    assignmentTitle: 'Midterm Exam: Graph Theory & Shortest Paths',
    triggerType: 'HIGH_WEIGHT_ASSESSMENT',
    channel: 'SMS',
    urgencyLevel: 'URGENT',
    subject: '🎯 48h Countdown: CS 301 Midterm Exam (25% of Grade)',
    body: 'Alex: CS 301 Midterm is in 48h (Aug 30, 10:00 AM). It is worth 25% of your grade. Tap here to view the 3-step AI Graph Theory study sprint: https://app.university.edu/student/study-plan',
    aiInsights: 'Recommended study focus: Dijkstra vs Bellman-Ford complexity and state space graph formulation.',
    createdAt: '2026-08-28T09:00:00Z',
    status: 'DELIVERED',
  },
  {
    id: 'rem_3',
    ruleId: 'rule_3',
    ruleName: 'Academic Safety Net (Grade < 70% Drop Alert)',
    studentId: 'stu_2',
    studentName: 'Jordan Lee',
    studentEmail: 'jordan.lee@university.edu',
    studentPhone: '+1 (555) 876-4321',
    courseId: 'crs_2',
    courseCode: 'MATH 240',
    triggerType: 'GRADE_BELOW_THRESHOLD',
    channel: 'EMAIL',
    urgencyLevel: 'URGENT',
    subject: '🚨 Academic Advisory Notice: Grade Alert for MATH 240 (58.4%)',
    body: 'Dear Jordan, your current score in MATH 240 is 58.4% (F). Prof. Marcus Brody (Advisor) and Dr. Michael Chang have been notified. Please attend Math Learning Center drop-in hours on Thursday 2-5 PM.',
    aiInsights: 'Critical intervention needed: Missing Homework 6 and failed Quiz 2. Advisor email dispatched.',
    createdAt: '2026-08-27T18:00:00Z',
    status: 'OPENED',
    openedAt: '2026-08-27T18:45:00Z',
  },
  {
    id: 'rem_4',
    ruleId: 'rule_5',
    ruleName: '24-Hour Urgent Deadline Nudge',
    studentId: 'stu_1',
    studentName: 'Alex Rivera',
    studentEmail: 'alex.rivera@university.edu',
    courseId: 'crs_2',
    courseCode: 'MATH 240',
    assignmentId: 'asg_201',
    assignmentTitle: 'Homework 6: Eigenvalues & Diagonalization',
    triggerType: 'UPCOMING_DEADLINE',
    channel: 'PUSH',
    urgencyLevel: 'HIGH',
    subject: '⏰ Due in 24 Hours: Homework 6',
    body: 'Reminder: Homework 6 for MATH 240 is due tonight at 11:59 PM. Estimated time: ~2.5 hrs.',
    createdAt: '2026-08-28T07:30:00Z',
    status: 'ACTION_TAKEN',
    openedAt: '2026-08-28T07:45:00Z',
    resolvedAt: '2026-08-28T08:50:00Z',
    resolutionNote: 'Student opened draft submission portal.',
  },
  {
    id: 'rem_5',
    ruleId: 'rule_6',
    ruleName: 'Excellence & Momentum Commendation',
    studentId: 'stu_3',
    studentName: 'Maya Chen',
    studentEmail: 'maya.chen@university.edu',
    courseId: 'crs_3',
    courseCode: 'BIO 110',
    triggerType: 'GRADE_IMPROVEMENT',
    channel: 'EMAIL',
    urgencyLevel: 'LOW',
    subject: '🎉 Outstanding Work in BIO 110 (98.0%)!',
    body: 'Great job Maya! Your work in Cellular & Molecular Biology is at 98.0% (A+). Keep up the wonderful leadership in your lab group.',
    createdAt: '2026-08-25T11:30:00Z',
    status: 'OPENED',
    openedAt: '2026-08-25T12:10:00Z',
  },
];

export const initialLMSIntegrations: LMSIntegrationConfig[] = [
  {
    id: 'lms_canvas',
    provider: 'CANVAS',
    name: 'University Canvas LMS (Main Campus)',
    status: 'CONNECTED',
    apiUrl: 'https://canvas.instructure.com/api/v1',
    apiKeyMasked: 'canvas_live_tok_••••••••••••94f2',
    coursesSyncedCount: 2,
    studentsSyncedCount: 142,
    lastSyncAt: '2026-08-28T09:15:00Z',
    autoSyncEnabled: true,
    syncIntervalMinutes: 30,
    syncLogs: [
      {
        timestamp: '2026-08-28T09:15:00Z',
        status: 'SUCCESS',
        message: 'Synchronized 4 assignments & 28 grade entries for CS 301 and MATH 240.',
        recordsProcessed: 32,
      },
      {
        timestamp: '2026-08-28T08:45:00Z',
        status: 'SUCCESS',
        message: 'Delta sync completed without conflicts.',
        recordsProcessed: 6,
      },
    ],
  },
  {
    id: 'lms_blackboard',
    provider: 'BLACKBOARD',
    name: 'Blackboard Learn Ultra (Science Division)',
    status: 'CONNECTED',
    apiUrl: 'https://blackboard.university.edu/learn/api/public/v1',
    apiKeyMasked: 'bb_sec_••••••••••••78b1',
    coursesSyncedCount: 1,
    studentsSyncedCount: 95,
    lastSyncAt: '2026-08-28T08:30:00Z',
    autoSyncEnabled: true,
    syncIntervalMinutes: 60,
    syncLogs: [
      {
        timestamp: '2026-08-28T08:30:00Z',
        status: 'SUCCESS',
        message: 'Synced BIO 110 rosters and Lab 3 gradebook columns.',
        recordsProcessed: 18,
      },
    ],
  },
  {
    id: 'lms_classroom',
    provider: 'GOOGLE_CLASSROOM',
    name: 'Google Classroom (Humanities & Writing)',
    status: 'CONNECTED',
    apiUrl: 'https://classroom.googleapis.com/v1',
    apiKeyMasked: 'gclass_oauth_••••••••••••66c3',
    coursesSyncedCount: 1,
    studentsSyncedCount: 68,
    lastSyncAt: '2026-08-28T07:45:00Z',
    autoSyncEnabled: false,
    syncIntervalMinutes: 120,
    syncLogs: [
      {
        timestamp: '2026-08-28T07:45:00Z',
        status: 'SUCCESS',
        message: 'Imported ENG 102 coursework and peer review grades.',
        recordsProcessed: 12,
      },
    ],
  },
  {
    id: 'lms_csv',
    provider: 'CUSTOM_CSV',
    name: 'Registrar SIS CSV / SIS Direct Feed',
    status: 'CONNECTED',
    apiUrl: 'sftp://sis.university.edu/exports/grades_fall2026.csv',
    apiKeyMasked: 'sftp_key_••••••••••••33e8',
    coursesSyncedCount: 4,
    studentsSyncedCount: 305,
    lastSyncAt: '2026-08-27T23:00:00Z',
    autoSyncEnabled: true,
    syncIntervalMinutes: 720,
    syncLogs: [
      {
        timestamp: '2026-08-27T23:00:00Z',
        status: 'SUCCESS',
        message: 'Full registrar gradebook verification matched 100% records.',
        recordsProcessed: 305,
      },
    ],
  },
];
